<a href="https://colab.research.google.com/github/loga-nancy/PythonBasic/blob/master/Untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
"""Use pandas to sort data frame ascending order with most calorie density"""
import pandas as pd
raw_data={
    'food':['barcon','strawberry','banna','spinatch'],
    'grams':[50,200,100,200],
    'calories':[271,64,89,46]
}

df=pd.DataFrame(raw_data, columns=['food','grams','calories'])
df

         food  grams  calories
0      barcon     50       271
1  strawberry    200        64
2       banna    100        89
3    spinatch    200        46

In [3]:
df['calorie_dense']=df['calories']/df['grams']

df.sort_values('calorie_dense',ascending=False)

         food  grams  calories  calorie_dense
0      barcon     50       271           5.42
2       banna    100        89           0.89
1  strawberry    200        64           0.32
3    spinatch    200        46           0.23